<h2>login using this form</h2>

<?php echo $this->tag->form("login/register"); ?>

   

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("login"); ?>
    </p>

</form>